# Generated by Django 3.2.6 on 2024-03-03 16:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyMixin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('usd', '$USD'), ('rub', 'Рубль')], default='rub', max_length=5, verbose_name='Валюта')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('percent_off', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Величина скидки в %')),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('currencymixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payments.currencymixin')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('price', models.PositiveIntegerField(verbose_name='Цена (коп)')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('name',),
            },
            bases=('payments.currencymixin',),
        ),
        migrations.CreateModel(
            name='ShippingTax',
            fields=[
                ('currencymixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payments.currencymixin')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('amount', models.PositiveIntegerField(verbose_name='Стоимость доставки (коп)')),
                ('behavior', models.CharField(choices=[('inclusive', 'Inclusive'), ('exclusive', 'Exclusive'), ('unexpected', 'Unexpected')], default='exclusive', max_length=15, verbose_name='Тип')),
                ('code', models.CharField(max_length=15, verbose_name='Налоговый код')),
            ],
            options={
                'verbose_name': 'Доставка',
                'verbose_name_plural': 'Доставка',
                'ordering': ('name',),
            },
            bases=('payments.currencymixin',),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='payments.discount', verbose_name='Скидка')),
                ('items', models.ManyToManyField(related_name='orders', to='payments.Item', verbose_name='Список заказов')),
                ('tax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='payments.shippingtax', verbose_name='Налог')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'default_related_name': 'orders',
            },
        ),
    ]
