# Generated by Django 3.2.6 on 2024-03-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20240301_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('usd', '$USD'), ('rub', 'Рубль')], default='rub', max_length=5, verbose_name='Валюта'),
        ),
    ]
